# Generated by Django 5.0.6 on 2024-07-17 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=100)),
                ('emp_role', models.CharField(max_length=25)),
                ('emp_contact', models.CharField(max_length=30)),
                ('emp_salary', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
